image: node

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

# test:
#   stage: test
#   cache:
#     paths:
#       - node_modules/
#     policy: pull
#   script:
#     - npm run test

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - cp dist/index.html dist/404.html
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main
